CREATE TABLE branch
(
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  phone   VARCHAR(255) NOT NULL
);

CREATE TABLE category
(
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL
);

CREATE TABLE product
(
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT         NOT NULL,
  sku         VARCHAR(50)    NOT NULL,
  name        VARCHAR(255)   NOT NULL,
  description VARCHAR(255)   NOT NULL,
  price       DECIMAL(19, 2) NOT NULL,
  active      BOOLEAN        NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_product_sku UNIQUE (sku),
  CONSTRAINT uq_product_name_category UNIQUE (name, category_id)
);

CREATE TABLE stock
(
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version             BIGINT    NOT NULL DEFAULT 0,
  product_id          BIGINT    NOT NULL,
  branch_id           BIGINT    NOT NULL,
  quantity            INTEGER   NOT NULL,
  reserved_quantity   INTEGER   NOT NULL,
  sold_quantity       INTEGER   NOT NULL,
  min_stock_threshold INTEGER   NOT NULL,
  max_stock           INTEGER   NOT NULL,
  last_update         TIMESTAMP NOT NULL,           -- Faltaba esta columna
  CONSTRAINT uq_stock_product_branch UNIQUE (product_id, branch_id)
);

ALTER TABLE product
  ADD CONSTRAINT fk_product_category
    FOREIGN KEY (category_id)
      REFERENCES category (id);

ALTER TABLE stock
  ADD CONSTRAINT fk_stock_product
    FOREIGN KEY (product_id)
      REFERENCES product (id);

ALTER TABLE stock
  ADD CONSTRAINT fk_stock_branch
    FOREIGN KEY (branch_id)
      REFERENCES branch (id);
